PROJECT_ID = ''
ITERATION_NAME = 'Iteration1'
PREDICTION_KEY = ''
ENDPOINT = ''
IMAGES_FOLDER = '../guessed-images/'

BOTTLING_RIGHT = ''
BOTTLING_LEFT = ''
BOTTLING_STRAIGHT = ''

HEAD_RIGHT = ''
HEAD_LEFT = ''
